### ISSUE TITLE
Payment method not generating correct xml

### ISSUE THREAD

**Issue by EvanRijn** [krukas/Mage2Gen#108]
I generated the code trought (mage2gen) so , i'm not sure it's 100% the same.

I have the output xml;
<item name="offline-payments" xsi:type="array">
<item name="component" xsi:type="string">Kantoore_Payment/js/view/payment/offline-payments</item>

to get it working on front i changed to; 
<item name="aanbetaling" xsi:type="array">
 <item name="component" xsi:type="string">Kantoore_Payment/js/view/payment/aanbetaling</item>

Where 'aanbetaling' is the  method name of the payment.

**Comment by krukas** [comment]
Hi @EvanRijn, can you give me the Mage2Gen share link.

**Comment by EvanRijn** [comment]
Goodmorning @krukas,

This is the link; https://mage2gen.com/load/2a7f25c3-091a-4cdd-a6e2-934e42865161

**Comment by EvanRijn** [comment]
```
<item name="offline-payments" xsi:type="array">
<item name="component" xsi:type="string">Kantoore_Payment/js/view/payment/offline-payments</item>

```

I see my mark up of the xml is missing.
