### ISSUE TITLE
Preferences missing for generated model

### ISSUE THREAD

**Issue by schmengler** [krukas/Mage2Gen#110]
If I generate a model, the following API interfaces are generated:

- `Api\Data\ModelInterface`
- `Api\Data\ModelSearchResultInterface`
- `Api\ModelRepository`

But the preferences in `di.xml` are missing and I have to add them manually. It would be nice if they were generated as well.

**Comment by krukas** [comment]
@schmengler Do you have a share link of the module where is goes wrong, for me the preferences are generated in the di.xml

**Comment by schmengler** [comment]
I should mention that I used the command line, not the web interface

**Comment by krukas** [comment]
I will update the lib in pypi, that should fix the problem
