### ISSUE TITLE
Generated admin controller fail to compile (production mode issue)

### ISSUE THREAD

**Issue by schmengler** [krukas/Mage2Gen#111]
The generated admin form controller `Save` fails to compile, with this error:

>                Extra parameters passed to parent construct: $coreRegistry.

The issue seems to be that it takes a `\Magento\Framework\Registry` argument, although does not extend the generated abstract controller.

**Comment by tuyennn** [comment]
@schmengler well I cannot find $coreRegistry on Save admin controller, seem that should be marked as fixed
