### ISSUE TITLE
Menu identifier "Experius_Test" instead of own module name

### ISSUE THREAD

**Issue by schmengler** [krukas/Mage2Gen#112]
In the generated abstract backend controller, there's this line in `initPage()`:

        $resultPage->setActiveMenu('Experius_Test::top_level')

It should be `${Vendor}_${Module}::top_level`

**Comment by krukas** [comment]
@schmengler do you have a Mage2Gen share link, only reference to Experius Test is in a load_module function that is not fully implemented and not used :)

**Comment by schmengler** [comment]
I should mention that I was using the command line tool, not the web
interface. Is there significant difference?

**Comment by krukas** [comment]
If you installed the command line tool with pip install its an old version. That reminds me to update the lib in pypi :)

**Comment by krukas** [comment]
I have updated the command line version, did this fixed it?
