### ISSUE TITLE
SearchResultInterface implementation missing for generated models

### ISSUE THREAD

**Issue by schmengler** [krukas/Mage2Gen#113]
An interface `Api\Data\ModelSearchResultInterface` is generated but without implementation, so `repository->getList()` does not work

**Comment by krukas** [comment]
@schmengler It uses the default Magento implementation Magento\Framework\Api\SearchResults you can find this in the di.xml preference

**Comment by schmengler** [comment]
I guess it should be a virtual type then. But when I used the command line
tool, there was no definition in di.xml and a real interface was generated
instead of a virtual type

**Comment by krukas** [comment]
Same as with #112, old version :)
