### ISSUE TITLE
Option to specify variables in CamelCase

### ISSUE THREAD

**Issue by LordZardeck** [krukas/Mage2Gen#135]
Currently if I provide my model column names as snake case (as they are, and should be, in the database), it names my PHP method parameters in snake case as well. This is against convention and it would be preferable to have an option to camelcase parameters.

**Comment by krukas** [comment]
Hi @LordZardeck, could you give a mage2gen share link where this happens, because it should use camelcase.

**Comment by LordZardeck** [comment]
@krukas Yes, here is an example: https://mage2gen.com/load/315f05c2-6344-4707-9c8c-f1c5679b8e33

You'll see the only way to get the constants to be named with underscores, is to snake case the property name, using Pascal case or camel case just makes the constants smashed together

**Comment by krukas** [comment]
@LordZardeck That is the intended use, you spicify the table column name/code in the field name. And then it will make it camelCase for places where it needs to be camelCase, for example the getters and setters.

**Comment by LordZardeck** [comment]
@krukas That's the issue though, it's not doing that for the variable names:

![](http://take.ms/fgm10)
