### ISSUE TITLE
Build repositories, models, and data models properly

### ISSUE THREAD

**Issue by LordZardeck** [krukas/Mage2Gen#136]
Core magento is still migrating toward this direction, but there should be 3 parts to a repository, the data model (which just is an in-memory typed container), the model (which handles talking to the resource model), and the repository. 

One problem with the current output from Mage2Gen for models is that the model (not a data model) implements the api model interface, but that interface is passed to the repository. The repository, in turn, attempts to grab the resource model. Problem is the interface does not specify a method for getting the resource model, nor should it. This breaks the design pattern set forth by magento.

**Comment by krukas** [comment]
@LordZardeck, This falls in the ticket #114 te make Mage2Gen compatible and conforms magento 2 and that this is an option to select
