### ISSUE TITLE
Copy File Path

### ISSUE THREAD

**Issue by lewisvoncken** [krukas/Mage2Gen#137]
It would be cool to have the feature to copy the file path so you can easily add a new plugin or observer to an existing module

Example:
class: Plugin\Magento\Catalog\Model\Config\Source\Product\Options\TierPrice
file: Plugin/Magento/Catalog/Model/Config/Source/Product/Options/TierPrice.php

**Comment by krukas** [comment]
or maybe on option to only donwload selected files.
