### ISSUE TITLE
Grid Collection is not created

### ISSUE THREAD

**Issue by shinesoftware** [krukas/Mage2Gen#143]
Hello,

I am a supporter of your fantastic project and I have found a new little bug. Seems to me that the Company\Module\Model\ResourceModel\Token\Grid\Collection in my case is not created from the wizard. Where I wrong?

![screenshot_024](https://user-images.githubusercontent.com/1553035/38085326-566f1dfa-3350-11e8-99bf-1d0cd7d8407a.png)

**Comment by krukas** [comment]
Hi @shinesoftware 

If you look at a few lines above you see that there is a virtualType for that class.
