### ISSUE TITLE
Use CollectionProcessorInterface in Repositories

### ISSUE THREAD

**Issue by LordZardeck** [krukas/Mage2Gen#152]
Magento has a simplified process for processing collections with search criteria instead of manually doing it, reducing complexity and the need to write extra code. Mage2Gen should follow this same process for it's generated repositories. An example can be seen here: https://github.com/magento/magento2/blob/2.2-develop/app/code/Magento/Catalog/Model/ProductRepository.php#L582

**Comment by dheesbeen** [comment]
Fixed by @lewisvoncken
