### ISSUE TITLE
Use DataModels instead of Models for search results items in repositories

### ISSUE THREAD

**Issue by LordZardeck** [krukas/Mage2Gen#153]
Repositories should be returning DataModels instead of Models in their search results. Magento has been slow to move this way, but it would be nice for Mage2Gen to support this ahead of the curve. An example of Magento doing this: https://github.com/magento/magento2/blob/2.2-develop/app/code/Magento/Customer/Model/ResourceModel/CustomerRepository.php#L373 and https://github.com/magento/magento2/blob/2.2-develop/app/code/Magento/Customer/Model/Customer.php#L310

**Comment by dheesbeen** [comment]
@LordZardeck @tuyennn @lewisvoncken 

I have created a example (blog) model which uses a separate data model (just like the customer model). This is the way i want to implemented in Mage2gen

https://github.com/experius/Magento-2-Module-Experius-Model-Repository-Example/commit/fb8752af6c286da08d346514c89c12dc400492a5

Let me know your thoughts 

@LordZardeck  is this what you meant?

**Comment by dheesbeen** [comment]
@krukas What are your thoughts?

experius/Magento-2-Module-Experius-Model-Repository-Example@fb8752a

**Comment by LordZardeck** [comment]
@dheesbeen I've been out of the office and just got back. I'll try to look at this this week

**Comment by tuyennn** [comment]
@dheesbeen That's a good sample, I've also finished implementing on the pull request relevant to your request. #208

**Comment by dheesbeen** [comment]
Done
