### ISSUE TITLE
Dependency inject resource model in repositories instead of using parameters

### ISSUE THREAD

**Issue by LordZardeck** [krukas/Mage2Gen#154]
Repositories generated by Mage2Gen rely on the interface to be an instance of the model in order to grab the resource model to perform database operations. The 2 issues with this are that `getResource` is deprecated, and the interface does not guarantee that the implementation will be a model with that method available, nor should it (see #153). Instead, Mage2Gen should dependency inject the resource model into the repository so that the repository has direct access to the ResourceModel for that Model.

**Comment by dheesbeen** [comment]
@LordZardeck Thanks for your issue's. You're absolutely right. We're are planning a hackathon. Main goal is to create a feature so we can create code for certain Magento versions. Which makes it possible to generate new 2.2 code without losing backwards compatibility. We will let you know when we updated the model snippets to the 2.2. standards. Thanks again.

**Comment by LordZardeck** [comment]
I agree that #152 is dependent on Magento 2.2 (which I didn't realize honestly), but #153 and this task are not (unless I'm missing something, which by all means let me know). These practices should be compatible with 2.1 and even 2.0.

**Comment by LordZardeck** [comment]
@dheesbeen can you private contact me about the hackathon? Our company has begun to move toward a vested interested in Mage2Gen and may be willing to participate and contribute.

**Comment by dheesbeen** [comment]
@LordZardeck I will contact you when we have a plan and a date!

**Comment by dheesbeen** [comment]
#158 Removed usage of getResource()
