### ISSUE TITLE
Is the website open source? Are we able to contribute to it as well?

### ISSUE THREAD

**Issue by LordZardeck** [krukas/Mage2Gen#155]
Like the title says, the website interface for Mage2Gen is much better for generating what I need right now, but I feel it's UI/UX could be improved. Is there another avenue for contributing to that, or is that proprietary?

**Comment by dheesbeen** [comment]
This year we will do a full redesign based on react. This will be open sourced. We will let know when we are ready

**Comment by LordZardeck** [comment]
@dheesbeen That's awesome news, if you need assistance getting that react site done, we have people who can assist in accelerating that.

**Comment by jmayoranotandil** [comment]
Hello @dheesbeen ! Have you opened the code?
