### ISSUE TITLE
Repository Interface is implemnted with lowercase letter instead of uppercase

### ISSUE THREAD

**Issue by robbertstevens** [krukas/Mage2Gen#156]

**Comment by LordZardeck** [comment]
This can be reproduced by creating any model and looking at the repository implementation. 

Example Project, look at Model/MyTestModelRepository.php: 
![](http://take.ms/CTqpO)
https://mage2gen.com/load/0ada157a-1485-43d0-bf1a-61d582793d11

**Comment by dheesbeen** [comment]
#157 Fixed
