### ISSUE TITLE
Copyright and package Information in each file

### ISSUE THREAD

**Issue by PrakashThapa** [krukas/Mage2Gen#16]
It would be great if there could be inserted a small copyright and package/method documentation like: 
At the top file
```php
/**
 * Some copyright text.
 *
 * @category    ***
 * @package     ***
 * @author      ****
 */
```
for the Method: 
```php
/**
 * Register user contexts.
     *
     * @param CompositeHelper $compositeHelper
     * @param UserContextInterface[] $userContexts
     * @return RETURN_TYPE
 */
 protected function add(UserContextInterface $userContext)
    {
        $this->userContexts[] = $userContext;
        return $this;
    }
```

**Comment by dheesbeen** [comment]
Good idea. We can add a copyright signature field to the profile for logged-in users.

**Comment by krukas** [comment]
License is added to the LIB, for the website we need to add a profile page for a custom license. I like the docstring allot too, i think i can add this next week (no promise :P)

**Comment by krukas** [comment]
Closing issue License and docstring is added to Core
