### ISSUE TITLE
Customer Attribute

### ISSUE THREAD

**Issue by useapp** [krukas/Mage2Gen#164]
If in Customer Attribute selecting frontend input type **price** i have error
PHP message: PHP Fatal error:  Uncaught Error: Class 'Magento\Eav\Model\Attribute\Data\Price' not found in /var/www/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:93

I change in mysql table **eav_attribute**  frontend_input to **text**  then started to work

Magento 2.1.11

**Comment by dheesbeen** [comment]
@useapp Thanks for reporting. We will let you know if we can reproduce it and if so, when it is fixed.

**Comment by lewisvoncken** [comment]
@useapp Magento 2 by default doesn't support the input type price for Customer attributes.

So the option has been deleted in PR #188 and #189 .
