### ISSUE TITLE
Ovverriding class method

### ISSUE THREAD

**Issue by piotrex** [krukas/Mage2Gen#168]
Can I override a class method from Magento or custom module with Mage2Gen? (e.g. like silksoftware module generator can?)

**Comment by krukas** [comment]
Hi @piotrex, you mean generating a preference, this is a small feature that is on the to-do list.

**Comment by krukas** [comment]
That is a di.xml preference, this is on the road map for next release #105 

I will close this issue because it's a duplicate.
