### ISSUE TITLE
Order Attribute?

### ISSUE THREAD

**Issue by mocodev** [krukas/Mage2Gen#193]
When do you expect this feature to be implemented?

**Comment by krukas** [comment]
@mocodev At the moment we are short on time, so I cant give you a timetable when someone is going to work on this. We happily accept pull requests, if you have questions for making this feature feel free to ask.

**Comment by lewisvoncken** [comment]
@mocodev creating Order Attributes has been added a few months ago. 

So now it is possible to add those through the Sales Attribute snippet but at the moment this is only creating the setup script.

But if you first generate the customer address attribute and select checkout billing or checkout shipping you get it in the checkout and you are ready to implement it.

See this example module:

https://mage2gen.com/load/cc7d3aae-7537-4ba2-8087-12915462a4fa?main_version=3
