### ISSUE TITLE
System Snippet | Tab name has to be alphanumeric

### ISSUE THREAD

**Issue by DavidLambauer** [krukas/Mage2Gen#20]
Steps to reproduce
--
1. Go to System Section
2. Add a System Configuration
3. Type "ImNotAsSmallAsYouThink" in the field "Tab"

Expected result
--
1. There should be no Error or if necessary an Error Message which makes more sense
2. Better Error Message would be "please use lowercase letters"

Actual result
--
1. Error Message is "Only alphanumeric"
2. http://recordit.co/eXeMYx0KoW

**Comment by krukas** [comment]
Thanks for the feedback, i have updated the validation and the message and this will go live tomorrow (little dev session :smile: )
