### ISSUE TITLE
Add GraphQl snippet

### ISSUE THREAD

**Issue by dheesbeen** [krukas/Mage2Gen#216]

**Comment by lewisvoncken** [comment]
the following input for GraphQL section in Mage2Gen:
- Module name
- Module dependencies
- one or more query names
- one or more mutation names

Based on that it should be possible to generate GraphQL module skeleton (edited)
the first 2 items are generic as far as I understand. So the only GraphQL specific input would be the last two fields.
and, by the way, we need to ask the type of those fields.
And potentially arguments, but this may become too complex with arguments (edited)

**Comment by dheesbeen** [comment]
Done!
