### ISSUE TITLE
Error delete model entity

### ISSUE THREAD

**Issue by textarea** [krukas/Mage2Gen#227]
- magento 2.2.6
- generated a "Vendor/Foo" test module with "Bar" model
- trying to delete "Bar" entity (ex: id #1) throw:
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Magento\Framework\Model\ResourceModel\Db\AbstractDb::delete() must be an instance of Magento\Framework\Model\AbstractModel, instance of Vendor\Foo\Model\Data\Bar given, called in /app/code/Vendor/Foo/Model/BarRepository.php on line 163 and defined in /vendor/magento/framework/Model/ResourceModel/Db/AbstractDb.php:441
Stack trace:
#0 /app/code/Vendor/Foo/Model/BarRepository.php(163): Magento\Framework\Model\ResourceModel\Db\AbstractDb->delete(Object(Vendor\Foo\Model\Data\Bar))
#1 /app/code/Vendor/Foo/Model/BarRepository.php(178): Vendor\Foo\Model\BarRepository->delete(Object(Vendor\Foo\Model\Data\Bar))
#2 /test.php(18): Vendor\Foo\Model\BarRepository->deleteById(1)
#3 {main}
  thrown in /vendor/magento/framework/Model/ResourceModel/Db/AbstractDb.php on line 441

**Comment by dheesbeen** [comment]
@textarea Thanks a lot for reporting. Fix is made. Ready for release.

**Comment by textarea** [comment]
Thanks @dheesbeen , waiting for new release.
Best regards

**Comment by dheesbeen** [comment]
@textarea Just released it
