### ISSUE TITLE
API snippet model not implementing interface

### ISSUE THREAD

**Issue by aimtell-paolo** [krukas/Mage2Gen#230]
Hi,

Thanks for this tool, helping me understand Mage2 👍  I am running into an issue with API snippet when testing in Magento 2.2

I am getting a Fatal Error _'Interface [...] not found'_ when running **setup:di:compile**. Tried fixing the path I was shown (Mage2Gen\Module\Model\Mage2Gen\Module\Api\ManagementInterface) to (Mage2Gen\Module\Api\ManagementInterface) but still getting the error. 

Checked past issues/fixes in Github, and saw that there was a merge [#187], but still running into this issue. I generated the code using https://mage2gen.com/ Would love to get a response.

**Comment by dheesbeen** [comment]
@aimtell-paolo  This snippet clearly needs some reviewing. We will let you know when its done.

**Comment by dheesbeen** [comment]
@aimtell-paolo Will be fixed in next release. The implement class only need a forward class at the beginning
