### ISSUE TITLE
Empty 'source' inside UpgradeData on product attribute

### ISSUE THREAD

**Issue by Jordaneisenburger** [krukas/Mage2Gen#259]
[
                    'type' => 'varchar',
                    'backend' => '',
                    'frontend' => '',
                    'label' => 'm2 price',
                    'input' => 'text',
                    'class' => '',
                    'source' => ,
                    'global' => 0,
                    'visible' => true,
                    'required' => true,
                    'user_defined' => true,
                    'default' => null,
                    'searchable' => false,
                    'filterable' => false,
                    'comparable' => false,
                    'visible_on_front' => true,
                    'used_in_product_listing' => false,
                    'unique' => false,
                    'apply_to' => '',
                    'system' => 1,
                    'group' => 'General',
                    'option' => array('values' => array(""))
                ]

**Comment by lewisvoncken** [comment]
@Jordaneisenburger this has been resolved earlier this year.
