### ISSUE TITLE
Conflict when adding multiple plugins in the same class but in different areas

### ISSUE THREAD

**Issue by peterkeijsers** [krukas/Mage2Gen#270]
**Problem**: When you would like to build two plugins that are for the same Class (for example the Magento\Catalog\Model\Product class) but one plugin is to be triggert in the frontend only, and one in the backend only you need to make two seperate classes, one for each of the plugins. Mage2gen currently addes both plugins in the same class which causes both plugins to trigger regarding there intended area.

![Bug in verschillende plugins op dezelfde class maar andere area](https://user-images.githubusercontent.com/3602913/55800785-c9fedb00-5ad4-11e9-9a91-ac422b3b83ef.png)

**possible solution**: When creating a plugin for a specific area. Put the plugin in a the appropriate area directory within the 'Plugins' directory. This has two advantages. One is that the scope is more apparent. The other is that this automatically creates a new class per area and conflicts as described above are solved. When a plugin is in the global area, than use no area directory in the classname. 

Examples:
_Experius/Plugins/etc/adminhtml/di.xml_
`<type name="Magento\Catalog\Model\Product"> 
        <plugin name="experius_plugins_afterGetSku" type="Experius\Plugins\Plugin\**AdminHtml**\Magento\Catalog\Model\Product" sortOrder="10" disabled="false" />
    </type>`

_Experius/Plugins/etc/di.xml_
`<type name="Magento\Catalog\Model\Product"> 
        <plugin name="experius_plugins_afterGetName" type="Experius\Plugins\Plugin\Magento\Catalog\Model\Product" sortOrder="10" disabled="false" />
    </type>`

_Experius/Plugins/etc/frontend/di.xml_
`<type name="Magento\Catalog\Model\Product"> 
        <plugin name="experius_plugins_afterGetName" type="Experius\Plugins\Plugin\**Frontend**\Magento\Catalog\Model\Product" sortOrder="10" disabled="false" />
    </type>`

For a working example check this Experius internal module: https://bitbucket.org/experius/mage2-module-experius-plugins/src/master/

**Comment by lewisvoncken** [comment]
@peterkeijsers dit is doorgevoerd.
