### ISSUE TITLE
Product attribute source model generates wrong classname

### ISSUE THREAD

**Issue by peterkeijsers** [krukas/Mage2Gen#271]
When creating a product attribute of type multiselect or dropdown with a custom source model. Mage2gen generates a source model name with underscores instead of CamelCased.

Look at the below example generating a product attribute with the following options:
**code**: 'sold_in_stores'
**frontend input**: multiselect or dropdown
**source model**: yes

Result: classname of sourcemodel is 'sold_in_stores.php' instead of 'SoldInStores.php'

![Screenshot from 2019-04-11 09-56-02](https://user-images.githubusercontent.com/3602913/55940526-980a8780-5c40-11e9-9394-8fd7535d4e92.png)

**Comment by lewisvoncken** [comment]
@peterkeijsers 
This has been resolved
