### ISSUE TITLE
Product attribute with custom source model creates bug in installData script

### ISSUE THREAD

**Issue by peterkeijsers** [krukas/Mage2Gen#272]
When generating a product option with a custom source model, the installData script adds an empty (broken!) arraykey 'option'

This results in the setup:upgrade script to fail

![Screenshot from 2019-04-11 10-03-06](https://user-images.githubusercontent.com/3602913/55940745-05b6b380-5c41-11e9-81db-5d71244225d2.png)

**Comment by lewisvoncken** [comment]
@peterkeijsers 
This has been resolved.
