### ISSUE TITLE
Sales attribute - UpgradeData wrong Qoute path

### ISSUE THREAD

**Issue by marretje** [krukas/Mage2Gen#275]
When generating a 'Sales Attribute'

Fill: 
'sales entity' => 'qoute'. 
'Upgrade data' => 'Yes'.

- In the upgrade method the type in $options is incorrectly filled
- Use path from 'QuoteSetupFactory' is wrong. Must be 'use Magento\Quote\Setup\QuoteSetupFactory;'

namespace Experius\Storelocator\Setup;

use Magento\Framework\Setup\UpgradeDataInterface;
use Magento\Framework\Setup\ModuleContextInterface;
use Magento\Framework\Setup\ModuleDataSetupInterface;
**use Magento\Sales\Setup\QuoteSetupFactory;**

class UpgradeData implements UpgradeDataInterface
{

    private $quoteSetupFactory;

    /**
     * Constructor
     *
     * @param \Magento\Sales\Setup\QuoteSetupFactory $quoteSetupFactory
     */
    public function __construct(quoteSetupFactory $quoteSetupFactory)
    {
        $this->quoteSetupFactory = $quoteSetupFactory;
    }

    /**
     * {@inheritdoc}
     */
    public function upgrade(
        ModuleDataSetupInterface $setup,
        ModuleContextInterface $context
    ) {
        $eavSetup = $this->quoteSetupFactory->create(['setup' => $setup]);

        if (version_compare($context->getVersion(), "1.0.1", "<")) {
        
            $options = ['type' => '**shipping_to_store**','length' => 255, 'visible' => false, 'required' => true,'grid' => false];
            $quoteSetup = $this->quoteSetupFactory->create(['setup' => $setup]);
            $quoteSetup->addAttribute('quote', 'shipping_to_store', $options);
        }
    }
}

**Comment by dheesbeen** [comment]
Confirmed. This snippets needs reviewing. Type should be text, varchar etc.

**Comment by lewisvoncken** [comment]
@dheesbeen and @marretje 

A fix has been applied for input_type and correct dependency injection.
