### ISSUE TITLE
ttribute from customer missing information is_user_defined

### ISSUE THREAD

**Issue by luanwebjump** [krukas/Mage2Gen#283]
In your constructor the code, also create attribute from customer missing information "is_user_defined"

**Comment by krukas** [comment]
@luanwebjump can you clarify which constructor this missing? A link to the Mage2Gen module with this problem can be helpful.

**Comment by luanwebjump** [comment]
In moment i don't remenber , please excuse me.
if i remember the problem, i create fork and send Pull Request.
thanks.
