### ISSUE TITLE
acl.xml is missing when create new module

### ISSUE THREAD

**Issue by vincent2090311** [krukas/Mage2Gen#290]
Hi 
I used your online tool to generate the module with system configuration but I dont see the file acl.xml. Could you manage to add that file to module automatically

**Comment by lewisvoncken** [comment]
Hi @vincent2090311 

Which snippet are you generating?

The acl.xml file is generated with the following snippet:

- Adminhtml Controller
- Model + Adminhtml Form/grid
- System / Config / Setting

**Comment by vincent2090311** [comment]
@lewisvoncken 
I see the acl with system config now. My network has some prob so I didnt see the update.
This issue can be closed
Thank you
