### ISSUE TITLE
Add module description to readme

### ISSUE THREAD

**Issue by dheesbeen** [krukas/Mage2Gen#321]

**Comment by lewisvoncken** [comment]
@dheesbeen 
This is added to the Main Functionalities section in the README.md
See screenshots below

![image](https://user-images.githubusercontent.com/6040343/68205772-620d6600-ffcb-11e9-9354-ea974f3f5ad5.png)

![image](https://user-images.githubusercontent.com/6040343/68205780-689bdd80-ffcb-11e9-927a-42c7d51ff92f.png)

**Comment by dheesbeen** [comment]
@lewisvoncken Whoops its already there
