### ISSUE TITLE
Admin Controller Index for model: constructor & execute method issue

### ISSUE THREAD

**Issue by cap340** [krukas/Mage2Gen#340]
I created a new module (for Magento 2.1) with Model and Controller using your module creator. It works as expected but there seems to be some errors inside `Controller\Adminhtml\MyModel\Index.php`
Here the generated code :  
<pre>
    /**
     * Constructor
     *
     * @param \Magento\Backend\App\Action\Context $context
     * @param \Magento\Framework\View\Result\PageFactory $resultPageFactory
     */
    public function __construct(
        \Magento\Backend\App\Action\Context $context,
        \Magento\Framework\View\Result\PageFactory $resultPageFactory
    ) {
        $this->resultPageFactory = $resultPageFactory;
        parent::__construct($context);

        $this->resultPageFactory = $resultPageFactory;
        parent::__construct($context);
    }
    
    /**
     * Index action
     *
     * @return \Magento\Framework\Controller\ResultInterface
     */
    public function execute()
    {
        return $this->resultPageFactory->create();

        
            $resultPage = $this->resultPageFactory->create();
            $resultPage->getConfig()->getTitle()->prepend(__("Request"));
            return $resultPage;
    }
</pre>
**__constructor**
<pre>
$this->resultPageFactory = $resultPageFactory;
parent::__construct($context);

$this->resultPageFactory = $resultPageFactory;
parent::__construct($context);
</pre>
**execute()** with 2 return

**Comment by lewisvoncken** [comment]
@cap340 
I can't reproduce the issue
