### ISSUE TITLE
Custom multiselect Catalog Category Attribute Class does not exist.

### ISSUE THREAD

**Issue by a4gpl** [krukas/Mage2Gen#46]
I have app/code/A4G/B2B/Model/Category/Attribute/Source/A4g_gtfeauters.php:
`<?php
namespace A4G\B2B\Model\Category\Attribute\Source;

class A4g_gtfeauters extends \Magento\Eav\Model\Entity\Attribute\Source\AbstractSource
{

    /**
     * @var array
     */
    protected $_optionsData;

    /**
     * Constructor
     *
     * @param array $options
     */
    public function __construct(\Psr\Log\LoggerInterface $logger, array $options)
    {
        $logger->addInfo('A4g_gtfeauters');
        $this->_optionsData = $options;
    }

    /**
     * getAllOptions
     *
     * @return array
     */
    public function getAllOptions()
    {
        if ($this->_options === null) {
            $this->_options = [
                ['value' => (string) 'CARP', 'label' => __('CARP')],
                ['value' => (string) 'CATFISH', 'label' => __('CATFISH')],
                ['value' => (string) 'COMPETITION', 'label' => __('COMPETITION')],
                ['value' => (string) 'FEEDER', 'label' => __('FEEDER')],
                ['value' => (string) 'FLY', 'label' => __('FLY')],
                ['value' => (string) 'ICE', 'label' => __('ICE')],
                ['value' => (string) 'MATCH', 'label' => __('MATCH')],
                ['value' => (string) 'SALTWATER', 'label' => __('SALTWATER')],
                ['value' => (string) 'SPINNIG', 'label' => __('SPINNIG')]
            ]
        }
        return $this->_options;
    }
}
`
generated by Mage2Gen, but still Magento shows me error:

Exception #0 (ReflectionException): Class A4G\B2B\Model\Category\Attribute\Source\A4g_gtfeauters does not exist.

Can you tell me what can make this kind of error? Logger function doesn't give any efect, error in code as well.

**Comment by krukas** [comment]
Hi @a4gpl, I thinks this happened because the class uses a underscore. I have fix this so it will generate a class in camelcase. also its missing a ; so that will give an error to, this is also fixed.
