### ISSUE TITLE
Menu issue when company name is the same for more than one extension installed.

### ISSUE THREAD

**Issue by shinesoftware** [krukas/Mage2Gen#49]
I am testing your software ... here I will report the issues and the suggestions ... :)

**Comment by shinesoftware** [comment]
1. If I create 2 modules and I try to save them in the same magento store I get an error when I try to open the new module:

```
    1 exception(s):
    Exception #0 (Magento\Framework\Exception\LocalizedException): Invalid Document 
    Element 'add': Duplicate key-sequence ['ShineSoftware::top_level'] in unique identity-constraint 'uniqueAddItemId'.
```
The problem is the menu id. Both module use: CompanyName:top_level.
I suppose that, if a user download 2 o more modules from your software maintaining the name of the company, the menu will show all the extensions installed.

**Comment by krukas** [comment]
This is something we cant fix in normal behaviour. Maybe we can add an advanced option to the snippets that create a menu item, to only use top_level item but dont create it.

**Comment by shinesoftware** [comment]
Yes it will be a good start. Let the user this option to create the menu as submenu.
