### ISSUE TITLE
Plugin naming convention

### ISSUE THREAD

**Issue by robbertstevens** [krukas/Mage2Gen#53]
Mage2gen uses the whole namespace as path too the plugin class, but Magento has a convention to use the following path `Vendor\Module\Plugin\{PluginClass}Plugin`

For example if you write a plugin for the following class: 
`Aheadworks\Blog\Model\ResourceModel\PostRepository` Mage2Gen will generate the class on the following path `Vendor\Module\Plugin\Aheadworks\Blog\Model\ResourceModel\PostRepository` 

But the Magento convention is `Vendor\Module\Plugin\PostRepositoryPlugin`

**Comment by krukas** [comment]
The problem with this is when you want to make a plugin for the same class name. So for now this is marked as wont fix.
