### ISSUE TITLE
Magento Compilation fails

### ISSUE THREAD

**Issue by shinesoftware** [krukas/Mage2Gen#55]
Hi guys,

when I try to compile the code

    ./n98-magerun2.phar setup:di:compile

I get this error:

    Extra parameters passed to parent construct: $coreRegistry.

The problem is this file:

    /Controller/Adminhtml/Wiki/Save.php

Best Regards

**Comment by joomi** [comment]
same for me:

Errors during compilation:
        Joomi\CategorySlider\Controller\Adminhtml\Category\Save
                Extra parameters passed to parent construct: $coreRegistry. File: /app/code/Joomi/CategorySlider/Controller/Adminhtml/Category/Save.php
Total Errors Count: 1

**Comment by VincentMarmiesse** [comment]
In your Save.php controller, just remove the __contruct param `\Magento\Framework\Registry $coreRegistry,` and replace the parent call
`parent::__construct($context, $coreRegistry);`

by 
`parent::__construct($context);`

see PR #69
