### ISSUE TITLE
Reorder models 

### ISSUE THREAD

**Issue by robbertstevens** [krukas/Mage2Gen#57]
When I make a new model I like to add attributes that have similar content close to each other. Now I cannot reorder the attributes in the model when I make additional attributes.

**Comment by krukas** [comment]
Ordering the snippet output is not possible, because each snippet doesn’t know about other snippets. Maybe we can add sort attribute to snippet class that points to a order param and sort by that before running

**Comment by krukas** [comment]
Duplicate of #51
