### ISSUE TITLE
 source_model Class does not exist 

### ISSUE THREAD

**Issue by Dhimant** [krukas/Mage2Gen#63]
So I tried to create a new module with one observer and few system settings. But something is wrong with system.xml I guess. Everything works expect custom source_model. If I look into system.log it says 
 Class Company\MyAwesomeModule\Model\Config\Source\My_awesome_clss does not exist.

So if I comment out the fields using custom source_model inside system.xml , the group does appear inside admin area under my tab->section. but it I uncomment nothing shows inside configuration. Although tab and section is there........I hope you get it what I am trying to say here.

**Comment by krukas** [comment]
The class name was invalid because of the lowercase, this is fixed.
