### ISSUE TITLE
Payment Method Not Working

### ISSUE THREAD

**Issue by jsmageto** [krukas/Mage2Gen#70]
if you try create a payment method, it will not show up on checkout page
i found incorrect generated layout xml

you can check at checkout_index_index.xml file

**Comment by jsmageto** [comment]
`<item name="component" xsi:type="string">Magento_OfflinePayments/js/view/payment/offline-payments</item><item name="methods" xsi:type="array">
        <item name="yourpaymentmethodname" xsi:type="array">
	     <item name="isBillingAddressRequired" xsi:type="boolean">true</item>
	</item>
</item>`

the correct layout script should be like this

`<item name="component" xsi:type="string">YourCompany_YourModule/js/view/payment/offline-payments</item><item name="methods" xsi:type="array">
        <item name="yourpaymentmethodname" xsi:type="array">
	     <item name="isBillingAddressRequired" xsi:type="boolean">true</item>
	</item>
</item>`

**Comment by kielsoft** [comment]
@jsmageto it will be better if you highlight the diff in the code you pasted.

**Comment by jsmageto** [comment]
last comment has been updated, please check
