### ISSUE TITLE
Please clarify the license of the generated code

### ISSUE THREAD

**Issue by fooman** [krukas/Mage2Gen#77]
Thanks for providing this code generator - after reading [this](https://softwareengineering.stackexchange.com/a/221607) and seeing that it might be arguable how much of the code (ie the templates) end up in the final generated output can you please clarify what the output is licensed under?

**Comment by krukas** [comment]
Thanks for the feedback. I'm not a specialist in licensing and don't have lawyers as friends. The code that is generated is free to use for whatever you want under every license you want. Only I don't know how to apply it to the current code/license. I see that you can create a license extension, but I'm no expert to create a valid extension.

So if you are someone else now how to do this, I would love to hear it or get a PR.

**Comment by fooman** [comment]
Thanks, this clarification 

> The code that is generated is free to use for whatever you want under every license you want.

works for me.

**Comment by krukas** [comment]
I Leave this issue open. Because if I read correctly we still need some license extension to clarify that.
