### ISSUE TITLE
Request does not match any route for web API

### ISSUE THREAD

**Issue by barjas** [krukas/Mage2Gen#89]
I generated a model with "Web api" Checkbox enabled. However when i try to use the api https://example.com/rest/V1/XXXX/YYYY, 
i get :
{
    "message": "Request does not match any route.",
    "trace": null
}

although am using the correct URL and parameters as defined in the webapi.xml

**Comment by krukas** [comment]
@barjas Can you send the Mage2Gen share link (in the save and download pop-up). I am away for couple of weeks en after that I can look into it.

**Comment by krukas** [comment]
For now I will close issue on replay i can look into it
