### ISSUE TITLE
use Factories instead of object Manager?

### ISSUE THREAD

**Issue by nei** [krukas/Mage2Gen#90]
The controller are being generated using the object Manager instead of Factories classes.

Any good reason for that?

**Comment by shinesoftware** [comment]
I suggest the factory too. I have changed all the controller code to fit this aim.

**Comment by krukas** [comment]
No reason, this was created when learning Magento 2 and controller snippet was ripped from the Magento CMS module (where the still use object manager :-) ).

**Comment by shinesoftware** [comment]
Ok so it's time to improve this awsome tool! 
I will help you to improve it by suggestion and snippet of code!
