### ISSUE TITLE
Collections & MassActions

### ISSUE THREAD

**Issue by shinesoftware** [krukas/Mage2Gen#92]
Hello guys,

I have found a problem in the NAMESPACE\MODULE\Model\ResourceModel\ENTITY when we use the MassAction in the Admin Grid.

You have to add this line:

    protected $_idFieldName = 'entity_id';

thanks

**Comment by krukas** [comment]
@shinesoftware I have checked the Magento code and _idFieldName  is set by _setMainTable that is called by _init. 

And Mage2Gen now creates:

protected function _construct()
    {
        $this->_init('module_entity', 'entity_id');
    }
