### ISSUE TITLE
Product Attribute for Virtual product type

### ISSUE THREAD

**Issue by shinesoftware** [krukas/Mage2Gen#94]
Hello Guys,

could I create an attribute for the Virtual product ?

![selezione_066](https://user-images.githubusercontent.com/1553035/29561398-93c92faa-8735-11e7-8a3b-68797430205a.png)

**Comment by krukas** [comment]
@shinesoftware you can add the product type code here https://github.com/krukas/Mage2Gen/blob/master/mage2gen/snippets/productattribute.py#L71
