### ISSUE TITLE
Model Fields Class have limitations

### ISSUE THREAD

**Issue by shinesoftware** [krukas/Mage2Gen#96]
Hi Krukas, 
I have found a strange limitation when I try to create more than 20 model fields.
I have checked the code but I have not found any constant to 20 model fields.

Any idea?

![selezione_065](https://user-images.githubusercontent.com/1553035/29569625-5c3eb266-8754-11e7-96c0-dfd595b2fadf.png)

thanks

**Comment by krukas** [comment]
@shinesoftware Yheaa that is an limitation I have added on the live server, to prevent large module DDOS. But we can increase this I think 100 would be fine, and is something the server can still handle I think :)

**Comment by shinesoftware** [comment]
Yes it is a good idea. One hundred of items doesn't create any issue about a ddos attack. A ddos attack needs thousands or more simultaneous requests.
