### ISSUE TITLE
Model groups and database table name

### ISSUE THREAD

**Issue by shinesoftware** [krukas/Mage2Gen#97]
Hi Krukas,

when you try to create more than one module, the Mage2Gen software creates the mysql tables using the setup class but there is a problem.

For instance: Take a look the Library project sample posted in the previous issue.

Just for testing:
We need to create a Library module and we need more than one data model. For instance:

The Module name: Library

The Models are:

- Books
- Category
- Tags

So I have created my models in this way: https://mage2gen.com/load/e9a12f34-9313-4b73-a6dd-1e650cd2ce99

Now the setup install will create 3 tables:

- mycompany_books
- mycompany_category
- mycompany_tags

Mage2Gen helps me to create all the models but the name of the classes and the name of the database tables could be create a bit of confusion when the project need more than 3 models.

So I have thought to group all the models using the project name:

- Library_Books
- Library_Category
- Library_Tags

but this solution creates a problem in the Magento folder structure.

Any hint?

**Comment by krukas** [comment]
We could do both so the table name is company_module_model, that way its always unique and clear where the database table comes from.

**Comment by shinesoftware** [comment]
Yes this is what I have done. In this case the problem is the folder structure:

![selezione_065](https://user-images.githubusercontent.com/1553035/29571699-2dd840da-875a-11e7-9742-d5af31e6a02d.png)

As you can see in this version of the module: https://mage2gen.com/load/150bac85-b5e5-46c0-bfe5-43d8ac7d847a the Blocks have been nested into the "Library_" folder.

**Comment by krukas** [comment]
You call your modul Subscriptions_Profile if you call it Profile the files will be correct, you dont need to prefix the model names with your module name

**Comment by shinesoftware** [comment]
I am writing 3 modules at the sametime :D I'm becoming crazy! 
If I delete the prefix from the name like in the sample project (https://mage2gen.com/load/150bac85-b5e5-46c0-bfe5-43d8ac7d847a/) the database tables are too much generic: 

For instance the Mage2Gen item:

    Mycompany_Category 

becomes a MySql table:

    mycompany_category

and it becomes a Php Class:

    MycompanyCategory

and the folder structure is correct but ... if you have two or more projects installed into your Magento 2 store with the same Namespace you need to identify the name of the class better. I mean that a developer could create a "Category" class for two different projects and when you execute the upgrade or the compilation code the setup will overwrite the common database table.

thanks

**Comment by tagesjump** [comment]
what if use table names like companyname_modulename_modelname so for example:
gurusoft_polls_users and do not change other things ?
